language: node_js
node_js:
  - "6"
deploy:
  provider: npm
  api_key:
    secure: wIEJfD3CAVubDpC1Ie4XA0XA7SQH0kFXwZ1vHrSqOjbIyOJjwvh8vAijERkHaWc+WYx1zpkJsX6UAMV7RY9M+AZKkfytTKNLm3w4P4AIWUTP8UP7vdi/3YeUOlyR4NW6pIbt26MRewQR7aTYgP+7EAiXlTAwYK6M+XKZ/k+L5CiQMU+SMUAb+RiVzjhsI3JjLyQLXfHPzIwWCRpwKn4QuY+7S+u9snobmnwpD+ZWMojrBTXnJGgv0LLDuMEuGKS0ssLpc/oo32JXFvHOODp8xuHjh98zTDDGw+DYKmbiyHNszOOLjHmeg2YrW8c/txsYx8Jb5TvMTFsSKLJ7hSA0+DrAx0TNwAaeJGVWZWhJJNML17aqIG8/zCOOPI4fqYHb/oKO7Ofzez+xnYdP3h2JCfh8ey85gHR4Qxw20V2h7QFa/sVvz4IhpS68OfcMvqsy4TrQg6RKrhz9BZdMOP0FfJAtIVRt72d0B8pjFnIHvP+Gb1ekSil+hDXytbPBjyfoMTxZf8XHcZkhCY2iHytI5SOenVHJH7VQE0gQ/MEZQ1qTxeBj3E8qoe5aCjOxFN9QNk8SEx16ZjkqP2rzUDbWCo0r6oIe3lQWeKf2I47/6eXZeh9E1ATe4yExDgLIAS+YBxdIp4SarpqgZfQvkrs6T3kbV1u/uAyyYZOzTsXF/Pc=
